import streamlit as st 
import pandas as pd 

st.title("Update data")
df = pd.read_csv("data.csv")
st.header("update data")
st.write(df)

st.sidebar.header("Opstion")
option_form = st.sidebar.form("option_form")
radius_mean = option_form.text_input('input radius mean')
texture_mean = option_form.text_input('input texture mean')
perimeter_mean = option_form.text_input('input perimeter mean')
area_mean = option_form.text_input('input area mean')
smoothness_mean = option_form.text_input('input smoothness mean')
compactness_mean = option_form.text_input('input compactness mean')
concavity_mean = option_form.text_input('input concavity mean')
concave_points_mean = option_form.text_input('input concave points mean')
symmetry_mean = option_form.text_input('input symmetry mean')
fractal_dimension_mean = option_form.text_input('input fractal dimension mean')
radius_se = option_form.text_input('input radius se')
texture_se = option_form.text_input('input texture se')
perimeter_se = option_form.text_input('input perimeter se')
area_se = option_form.text_input('input area se')
smoothness_se = option_form.text_input('input smoothness se')
compactness_se = option_form.text_input('input compactness se')
concavity_se = option_form.text_input('input concavity se')
concave_points_se = option_form.text_input('input concave points se')
symmetry_se = option_form.text_input('input symmetry se')
fractal_dimension_se = option_form.text_input('input fractal dimension se')
radius_worst = option_form.text_input('input radius worst')
texture_worst = option_form.text_input('input texture worst')
perimeter_worst = option_form.text_input('input perimeter worst')
area_worst = option_form.text_input('input area worst')
smoothness_worst = option_form.text_input('input smothness worst')
compactness_worst = option_form.text_input('input compactness worst')
concavity_worst = option_form.text_input('input concavity worst')
concave_points_worst = option_form.text_input('input concave points worst')
symmetry_worst = option_form.text_input('input symmetry worst')
fractal_dimension_worst = option_form.text_input('input fractal dimension worst')
if add_data:
    new_data = {}
    df.append(new_data, ignore_index=True)
    df.to_csv("data.csv", index=False)